### ISSUE TITLE
Read error: error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac

### ISSUE THREAD

**Issue by eleksir** [gryphonshafer/Bot-IRC#16] opened 2021-08-06 13:59 UTC
Dunno how to correctly name ticket...

Anyway, it's easily reproducible - setup bot to try to connect to ssl port of libera.chat, make it to join to some channel and try to talk with it instead of answer you'll recieve:

```
20210806.1600 < eleksir> !ping
20210806.1600 -!- aleesa [~aleesa@xxx.xxx.xxx.xxx] has quit [Read error: error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac]
```

and in bot logs you'll get:
```
[06/Aug/2021:16:00:26 +0300] :NickServ!NickServ@services.libera.chat NOTICE aleesa :You are now identified for aleesa.
[06/Aug/2021:16:00:26 +0300] :NickServ!NickServ@services.libera.chat NOTICE aleesa :Last login from: ~eleksir@XXX.XXX.XXX.XXX on Aug 01 13:43:30 2021 +0000.
[06/Aug/2021:16:00:44 +0300] :eleksir!~UNIX@XXX.XXX.XXX.XXX PRIVMSG ##mychannel :!ping
[06/Aug/2021:16:00:44 +0300] <<< PRIVMSG #mychannel :Pong.
bash-5.1$ 
```

as you can see bot in this case dies. And also message was lost.

**Comment by gryphonshafer** [comment] 2021-09-24 22:43
I'm not able to reproduce this. This looks like an old bug in openssl. It's far deeper than the scope of Bot::IRC, so I'm going to close this ticket. You could try updating openssl locally if it isn't already. Bot::IRC uses IO::Socket::SSL, so maybe check that for latest version as well.

**Closed as completed by gryphonshafer** 2021-09-24 22:43 UTC
